version: '3'

services:
  mongodb:
    image: mongo:4.0.10
    # environment:
      # MONGO_DATA_DIR: /data/db
      # MONGO_LOG_DIR: /var/log/mongo
      # MONGODB_USER: user 
      # MONGODB_PASS: pass
      # MONGO_INITDB_ROOT_USERNAME: user
      # MONGO_INITDB_ROOT_PASSWORD: pass
      # MONGO_ROOT_USERNAME: user
      # MONGO_ROOT_PASSWORD: pass
    volumes:
      - ./deployment/mongo/mongod.conf:/etc/mongod.conf
      - ./volumes/mongodb/var/lib/mongodb:/var/lib/mongodb
      - ./volumes/mongodb/var/log/mongodb:/var/log/
      - ./volumes/mongodb/data/db/:/data/db/
    ports:
      - 27017:27017
    command: mongod --smallfiles
  # mongoclient:
  #   image: mongoclient/mongoclient:latest
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 3300:3000