version: '3'

services:

  mongodb-arbitrator:
    image: mongo:4.0.10
    volumes:
      - ./deployment/mongo/mongod.conf:/etc/mongod.conf
      - ./volumes/mongodb-artitrator/var/lib/mongodb:/var/lib/mongodb
      - ./volumes/mongodb-artitrator/var/log/mongodb:/var/log/
      - ./volumes/mongodb-artitrator/data/db/:/data/db/
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "TestMongoReplicaSet" ]

  mongodb-replica-1:
    image: mongo:4.0.10
    volumes:
      - ./deployment/mongo/mongod.conf:/etc/mongod.conf
      - ./volumes/mongodb-replica-1/var/lib/mongodb:/var/lib/mongodb
      - ./volumes/mongodb-replica-1/var/log/mongodb:/var/log/
      - ./volumes/mongodb-replica-1/data/db/:/data/db/
    ports:
      - 27117:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "TestMongoReplicaSet" ]

  mongodb-replica-2:
    image: mongo:4.0.10
    volumes:
      - ./deployment/mongo/mongod.conf:/etc/mongod.conf
      - ./volumes/mongodb-replica-2/var/lib/mongodb:/var/lib/mongodb
      - ./volumes/mongodb-replica-2/var/log/mongodb:/var/log/
      - ./volumes/mongodb-replica-2/data/db/:/data/db/
    ports:
      - 27217:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "TestMongoReplicaSet" ]

  rockmongo:
    image: weshigbee/rockmongo
    environment:
      MONGO_SERVER: mongodb-replica-1
    ports:
      - 8010:80
    depends_on:
      - mongodb-replica-1
